### ISSUE TITLE
Question about  MolGen_Model loadmode

### ISSUE THREAD

**Issue by hirose125** [MingyuanXu/TreeInvent-Community#1]
Hello

Thank you for the wonderful implementation and sample code. Currently,
 I am experimenting with Finetune_RL_examples. 
When the 'loadtype' of MolGen_Model is set to 'Perepoch', 
is the file "/model/node_add_model_perepoch.cpk" generated during Basic_train_examples?

**Comment by MingyuanXu** [comment]
Yes! The pre-trained model name should be /model/node_add_model_perepoch.cpk.

**Comment by hirose125** [comment]
Thank you for your reply.
I have confirmed that node_add_model_perepoch.cpk has been generated.
I'm getting quite a hang of how to use it.
Thank you for the wonderful tool.
